version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
